=== apineiroandion/LMSXI/XSD/exercicio1.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
targetNamespace="Exercicio1.xml">
    <xsd:element name="persoa">
        <xsd:complexType>
            <xsd:element name="dni" type="xsd:string{9}"/> (cambiar esto)
            <xsd:element name="nome" type="xsd:string"/>
            <xsd:element name="estadoCivil" type="xsd:string">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="Soltero | Casado | Viudo"/>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="empresa">
                <xsd:complexType>
                    <xsd:element name="nome" type="xsd:string"/>
                    <xsd:element name="url" type="xsd:string"/>
                    <xsd:element name="telefono">
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:> (acabar esto)
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:elememnt>
                </xsd:complexType>
            </xsd:element>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== apineiroandion/LMSXI/XSD/Exercicio1.xml
<?xml version = "1.0" encoding = "UTF-8"?>
xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation = "exercicio1.xsd" >
<persoa>
    <dni>111111111</dni>
    <nome>Carlos Pacheco</nome>
    <estadoCivil>Soltero</estadoCivil>
    <empresa>
        <nome>Marvel</nome>
        <url>http://www.marvel.com</url>
        <telefono>+34916753306</telefono>
    </empresa>
</persoa>
